server/zanata-war/src/main/java/org/zanata/action/SendEmailAction.java
/*
 * Copyright 2010, Red Hat, Inc. and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.zanata.action;

import java.io.Serializable;
import java.security.Principal;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import org.hibernate.validator.Email;
import org.jboss.seam.ScopeType;
import org.jboss.seam.annotations.Create;
import org.jboss.seam.annotations.In;
import org.jboss.seam.annotations.Logger;
import org.jboss.seam.annotations.Name;
import org.jboss.seam.annotations.Scope;
import org.jboss.seam.core.ResourceBundle;
import org.jboss.seam.faces.FacesMessages;
import org.jboss.seam.faces.Renderer;
import org.jboss.seam.international.LocaleSelector;
import org.jboss.seam.log.Log;
import org.jboss.seam.security.RunAsOperation;
import org.jboss.seam.security.management.IdentityManager;
import org.jboss.seam.security.management.JpaIdentityStore;
import org.zanata.ApplicationConfiguration;
import org.zanata.common.LocaleId;
import org.zanata.dao.PersonDAO;
import org.zanata.model.HAccount;
import org.zanata.model.HLocale;
import org.zanata.model.HLocaleMember;
import org.zanata.model.HPerson;
import org.zanata.service.LocaleService;

/**
 * Sends an email to a specified role.
 * 
 * Currently just sends an email to admin.
 * 
 * @author damason@redhat.com
 * 
 */
@Name("sendEmail")
@Scope(ScopeType.PAGE)
public class SendEmailAction implements Serializable
{
   private static final long serialVersionUID = 1L;

   private static final String EMAIL_TYPE_CONTACT_ADMIN = "contact_admin";
   private static final String EMAIL_TYPE_CONTACT_COORDINATOR = "contact_coordinator";
   private static final String EMAIL_TYPE_REQUEST_TO_JOIN = "request_to_join_language_team";

   private static final String ADMIN_EMAIL_TEMPLATE = "/WEB-INF/facelets/email/email_admin.xhtml";
   private static final String COORDINATOR_EMAIL_TEMPLATE = "/WEB-INF/facelets/email/email_coordinator.xhtml";
   private static final String REQUEST_TO_JOIN_EMAIL_TEMPLATE = "/WEB-INF/facelets/email/email_request_to_join.xhtml";

   @In
   private ApplicationConfiguration applicationConfiguration;

   @In
   private PersonDAO personDAO;

   @In
   private IdentityManager identityManager;

   @In(required = true, value = JpaIdentityStore.AUTHENTICATED_USER)
   private HAccount authenticatedAccount;

   @In
   private LocaleService localeServiceImpl;

   @In
   private LocaleSelector localeSelector;

   @Logger
   private Log log;

   @In(create = true)
   private Renderer renderer;

   private String fromName;
   private String fromLoginName;
   private String replyEmail;
   private String subject;
   private String message;
   private String emailType;
   private String toName;
   private String toEmailAddr;
   private String language;
   private HLocale locale;

   @Create
   public void onCreate()
   {
      if (authenticatedAccount == null)
      {
         log.error("SendEmailAction failed to load authenticated account");
         return;
      }
      fromName = authenticatedAccount.getPerson().getName();
      fromLoginName = authenticatedAccount.getUsername();
      replyEmail = authenticatedAccount.getPerson().getEmail();

      subject = "";
      message = "";
   }

   public String getFromName()
   {
      return fromName;
   }

   public void setFromName(String name)
   {
      fromName = name;
   }

   public String getFromLoginName()
   {
      return fromLoginName;
   }

   public void setFromLoginName(String fromLoginName)
   {
      this.fromLoginName = fromLoginName;
   }

   @Email
   public String getReplyEmail()
   {
      return replyEmail;
   }

   @Email
   public void setReplyEmail(String replyEmail)
   {
      this.replyEmail = replyEmail;
   }

   public String getSubject()
   {
      return subject;
   }

   public void setSubject(String subject)
   {
      this.subject = subject;
   }

   public String getHtmlMessage()
   {
      return message;
   }

   public void setHtmlMessage(String encodedMessage)
   {
      this.message = encodedMessage;
   }

   public String getEmailType()
   {
      return emailType;
   }

   public void setEmailType(String emailType)
   {
      this.emailType = emailType;
   }

   public String getToName()
   {
      return toName;
   }

   public String getToEmailAddr()
   {
      return toEmailAddr;
   }

   public String getLanguage()
   {
      return language;
   }

   public void setLanguage(String language)
   {
      this.language = language;
      locale = localeServiceImpl.getByLocaleId(new LocaleId(language));
   }

   public HLocale getLocale()
   {
      return locale;
   }

   private List<HPerson> coordinators;

   private List<HPerson> getCoordinators()
   {
      coordinators = new ArrayList<HPerson>();
      
      for (HLocaleMember member : locale.getMembers())
      {
         if (member.isCoordinator())
         {
            coordinators.add(member.getPerson());
         }
      }
      return coordinators;
   }

   private List<HPerson> admins;

   /**
    * 
    * @return a list of admin users
    */
   private List<HPerson> getAdmins()
   {
      // required to read admin users for a non-admin session
      new RunAsOperation()
      {
         @Override
         public void execute()
         {
            admins = new ArrayList<HPerson>();
            for (Principal admin : identityManager.listMembers("admin"))
            {
               admins.add(personDAO.findByUsername(admin.getName()));
            }
         }
      }.addRole("admin").run();

      return admins;
   }

   /**
    * Sends the email by rendering an appropriate email template with the values
    * in this bean.
    * 
    * @return a view to redirect to. This should be replaced with configuration
    *         in pages.xml
    */
   public String send()
   {
      Locale pervLocale = localeSelector.getLocale();
      localeSelector.setLocale(new Locale("en"));

      try
      {
         if (emailType.equals(EMAIL_TYPE_CONTACT_ADMIN))
         {
            sendToAdminEmails(ADMIN_EMAIL_TEMPLATE);
            return "success";
         }
         else if (emailType.equals(EMAIL_TYPE_CONTACT_COORDINATOR))
         {
            sendToLanguageCoordinators(COORDINATOR_EMAIL_TEMPLATE);
            return "success";
         }
         else if (emailType.equals(EMAIL_TYPE_REQUEST_TO_JOIN))
         {
            sendToLanguageCoordinators(REQUEST_TO_JOIN_EMAIL_TEMPLATE);
            return "success";
         }
         else
         {
            throw new Exception("Invalid email type: " + emailType);
         }
      }
      catch (Exception e)
      {
         FacesMessages.instance().add("There was a problem sending the message: " + e.getMessage());
         log.error("Failed to send email: fromName '{0}', fromLoginName '{1}', replyEmail '{2}', subject '{3}', message '{4}'", e, fromName, fromLoginName, replyEmail, subject, message);
         return "failure";
      }
      finally
      {
         localeSelector.setLocale(pervLocale);
      }
   }

   private void sendToLanguageCoordinators(String emailTemplate)
   {

      List<HPerson> coordinators = getCoordinators();
      if (!coordinators.isEmpty())
      {
         for (HPerson coord : coordinators)
         {
            toName = coord.getName();
            toEmailAddr = coord.getEmail();
            renderer.render(emailTemplate);
         }
         log.info("Sent language team coordinator email: fromName '{0}', fromLoginName '{1}', replyEmail '{2}', subject '{3}', message '{4}', language '{5}'", fromName, fromLoginName, replyEmail, subject, message, language);
         FacesMessages.instance().add("#{messages['jsf.email.coordinator.SentNotification']}");
      }
      else
      {
         sendToAdminEmails(emailTemplate);
      }
   }

   /**
    * sends emails to configured admin emails for server, or admin users if no
    * server emails are configured.
    * 
    * Throws exception if there is a problem.
    * 
    * @param emailTemplate
    */
   private void sendToAdminEmails(String emailTemplate)
   {
      List<String> adminEmails = applicationConfiguration.getAdminEmail();
      if (!adminEmails.isEmpty())
      {
         toName = ResourceBundle.instance().getString("jsf.ZanataAdministrator");
         for (String email : adminEmails)
         {
            toEmailAddr = email;
            renderer.render(emailTemplate);
         }
         log.info("Sent server admin email: fromName '{0}', fromLoginName '{1}', replyEmail '{2}', subject '{3}', message '{4}'", fromName, fromLoginName, replyEmail, subject, message);
         FacesMessages.instance().add("#{messages['jsf.email.admin.SentNotification']}");
      }
      else
      {
         sendToAdminUsers(emailTemplate);
      }
   }

   /**
    * Emails admin users with given template
    * 
    * @param emailTemplate
    */
   private void sendToAdminUsers(String emailTemplate)
   {
      for (HPerson admin : getAdmins())
      {
         toName = admin.getName();
         toEmailAddr = admin.getEmail();
         renderer.render(emailTemplate);
      }

server/zanata-war/src/main/webapp/language/contact_coordinator.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
   xmlns:s="http://jboss.com/products/seam/taglib"
   xmlns:ui="http://java.sun.com/jsf/facelets"
   xmlns:f="http://java.sun.com/jsf/core"
   xmlns:h="http://java.sun.com/jsf/html"
   xmlns:a4j="http://richfaces.org/a4j"
   xmlns:rich="http://richfaces.org/rich"
   template="/WEB-INF/layout/template.xhtml">

   <ui:param name="showGlobalMessages" value="true"/>
   
   <ui:define name="center_content">
      <rich:jQuery selector="#tab_tribes" query="addClass('ui-tabs-selected')" />
      <h:form>
         <s:token allowMultiplePosts="true" />
         <h1>#{messages['jsf.contactLanguageTeamCoordinatorForLocale']}</h1>
         <rich:panel>
            
            <s:decorate id="nameField" template="../WEB-INF/layout/display.xhtml">
               <ui:define name="label">#{messages['jsf.email.From']}</ui:define>
               <h:outputText id="senderName" value="#{sendEmail.fromName}"
                             required="true" />
            </s:decorate>

            <s:decorate id="replyEmailField" template="../WEB-INF/layout/display.xhtml">
               <ui:define name="label">#{messages['jsf.email.ReplyAddress']}<br/>#{messages['jsf.email.ReplyAddress.description']}</ui:define>
               <h:outputText id="email" value="#{sendEmail.replyEmail}" required="true" />
            </s:decorate>

            <s:decorate id="subjectField"
                        template="../WEB-INF/layout/edit.xhtml">
               <ui:define name="label">#{messages['jsf.email.Subject']}</ui:define>
               <h:inputText id="subject" value="#{sendEmail.subject}"
                            required="true" />
            </s:decorate>

            <s:decorate id="messageField"
                        template="../WEB-INF/layout/edit.xhtml">
               <ui:define name="label">#{messages['jsf.email.MessageBody']}</ui:define>
               <rich:editor id="message" width="400" height="300"
                            style="width:400px;" required="true"
                            value="#{sendEmail.htmlMessage}" viewMode="visual"
                            useSeamText="false" configuration="richeditor" theme="advanced">
               </rich:editor>
            </s:decorate>

            <div style="clear: both"></div>
            <div class="actionButtons">
               <h:commandButton id="send" value="#{messages['jsf.email.Send']}"
                                action="#{sendEmail.send}" />

               <s:button id="cancel" value="#{messages['jsf.Cancel']}"
                         propagation="none" action="#{sendEmail.cancel}" />
            </div>

         </rich:panel>
      </h:form>

   </ui:define>

</ui:composition>

server/zanata-war/src/main/webapp/language/home.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:s="http://jboss.com/products/seam/taglib"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:rich="http://richfaces.org/rich"
    template="../WEB-INF/layout/template.xhtml">

    <ui:define name="left_content">
      <rich:panel rendered="#{identity.loggedIn}">
        <f:facet name="header">#{messages['jsf.Actions']}</f:facet>
      </rich:panel>
    </ui:define>

    <ui:define name="center_content">
        <rich:jQuery selector="#tab_tribes" query="addClass('ui-tabs-selected')" />
        <h1>#{messages['jsf.Languages']}</h1>
        <h:form>
            <rich:dataTable id="latestTribes" value="#{supportedLanguageAction.supportedLanguages}" var="language">
                <rich:column sortBy="#{language.localeId.id}">
                    <f:facet name="header">#{messages['jsf.Language']}</f:facet>
                    <s:link view="/language/language.xhtml" propagation="none" value="#{language.localeId.id}" styleClass="table_link">
                        <f:param name="id" value="#{language.localeId.id}" />
                    </s:link>
                </rich:column>
                <rich:column sortBy="#{language.retrieveDisplayName()}">
                    <f:facet name="header">#{messages['jsf.Name']}</f:facet>
                    #{language.retrieveDisplayName()}
                </rich:column>
                <rich:column >
                    <f:facet name="header">#{messages['jsf.NativeName']}</f:facet>
                    #{language.retrieveNativeName()}
                </rich:column>
                <rich:column sortBy="#{language.members.size}">
                    <f:facet name="header">#{messages['jsf.Members']}</f:facet>
                    #{language.members.size}
                </rich:column>
            </rich:dataTable>
        </h:form>
    </ui:define>
</ui:composition>

server/zanata-war/src/main/webapp/language/language.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:s="http://jboss.com/products/seam/taglib"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:rich="http://richfaces.org/rich"
    xmlns:a4j="http://richfaces.org/a4j"
    template="../WEB-INF/layout/template.xhtml">

    <ui:define name="center_content">
        <rich:jQuery selector="#tab_tribes" query="addClass('ui-tabs-selected')" />
        <a4j:form>
            <rich:panel id="memberPanel" >
                <h1>#{languageTeamAction.locale.retrieveNativeName()}</h1>
                <p>#{messages['jsf.SizeMembers']}</p>
                <rich:dataTable
                    id="threads"
                    value="#{languageTeamAction.locale.members.toArray()}"
                    var="member" 
                    rendered="#{not empty languageTeamAction.locale.members}"
                    sortMode="single">
                  <rich:column id="usernameCol" width="auto" sortBy="#{member.person.account.username}" sortOrder="ASCENDING">
                    <f:facet name="header">#{messages['jsf.Username']}</f:facet>
                    #{member.person.account.username}
                  </rich:column>
                  <rich:column width="auto" sortBy="#{member.person.name}">
                    <f:facet name="header">#{messages['jsf.Name']}</f:facet>
                    #{member.person.name}
                  </rich:column>
                  <rich:column width="auto" rendered="#{languageTeamAction.checkPermission('manage-language-team')}">
                    <f:facet name="header">#{messages['jsf.Email']}</f:facet>
                    <h:outputText>
                        #{member.person.email}
                    </h:outputText>
                  </rich:column>
                  <rich:column width="auto" styleClass="centered">
                    <f:facet name="header">#{messages['jsf.Coordinator']}</f:facet>
                    <h:selectBooleanCheckbox value="#{member.coordinator}"
                        rendered="#{languageTeamAction.checkPermission('manage-language-team')}">
                        <a4j:support event="onclick"
                            ajaxSingle="true"
                            reRender="threads"
                            action="#{languageTeamAction.saveTeamCoordinator(member)}"/>
                    </h:selectBooleanCheckbox>
                    <h:outputText rendered="#{not languageTeamAction.checkPermission('manage-language-team') and member.coordinator}">
                        <div class="checkmark"/>
                    </h:outputText>
                  </rich:column>
                  <rich:column width="auto" styleClass="centered"
                      rendered="#{languageTeamAction.checkPermission('manage-language-team')}">
                      <f:facet name="header">#{messages['jsf.Actions']}</f:facet>
                      <a4j:commandButton value="#{messages['jsf.Remove']}"
                          action="#{languageTeamAction.removeMembership(member)}"
                          reRender="threads"
                          onclick="this.disabled=true"
                          oncomplete="this.disabeld=false"/>
                  </rich:column>
                </rich:dataTable>
            </rich:panel>
        </a4j:form>
    </ui:define>

    <ui:define name="left_content">

      <rich:panel id="actionPanel" rendered="#{identity.loggedIn}">
        <f:facet name="header">
          #{messages['jsf.Actions']}
        </f:facet>
        <a4j:form id="Language_team_member_toggle_form" ajaxSubmit="true" reRender="actionPanel,tribesTabDiv,memberPanel">
          <a4j:commandLink id="Join" styleClass="action_link" action="#{languageTeamAction.joinTribe}" rendered="#{not languageTeamAction.contained and s:hasRole('admin')}">
            #{messages['jsf.JoinLanguageTeam']}
            <s:conversationId name="id" value="#{languageTeamAction.language}"/>
          </a4j:commandLink>
          <a4j:commandLink id="Leave" styleClass="action_link" action="#{languageTeamAction.leaveTribe}" rendered="#{languageTeamAction.contained}">
            #{messages['jsf.LeaveLanguageTeam']}
            <s:conversationId name="id" value="#{languageTeamAction.language}"/>
          </a4j:commandLink>
          <s:link styleClass="action_link" value="#{messages['jsf.RequestToJoinLanguageTeam']}" view="/language/join/#{languageTeamAction.language}" rendered="#{identity.loggedIn and not languageTeamAction.contained}" />
            <!--
          <s:link styleClass="action_link" value="#{messages['jsf.contactLanguageTeamCoordinator']}" view="/language/contact_coordinator.xhtml" propagation="none"  rendered="#{identity.loggedIn}">
            using this param is not as clean as I'd like, but seems to be the only way to get a literal
                 value into a bean. Ideally this should be inserted in pages.xml somehow
            <f:param name="emailType" value="contact_coordinator" />
            <f:param name="id" value="#{languageTeamAction.language}" />
          </s:link>
                 -->
          <s:link styleClass="action_link" value="#{messages['jsf.contactLanguageTeamCoordinator']}" view="/language/contact/#{languageTeamAction.language}" propagation="none"  rendered="#{identity.loggedIn}" />
          <h:outputText rendered="#{languageTeamAction.checkPermission('manage-language-team')}">
            <a href="#" class="action_link" onclick="#{rich:component('userAddPanel')}.show()">#{messages['jsf.AddTeamMember']}</a>
          </h:outputText>
        </a4j:form>
      </rich:panel>

      <rich:modalPanel id="userAddPanel" width="530" height="320">
        <f:subview id="personSearch">
          <a4j:form>
            <h1>Find Users To Add</h1>
            <p>
              <h:inputText value="#{languageTeamAction.searchTerm}" />
              <a4j:commandButton value="#{messages['jsf.Search']}"
                                 action="#{languageTeamAction.searchForTeamMembers}"
                                 reRender="searchResults"
                                 status="searchStatus" />
              <h:commandButton value="#{messages['jsf.Close']}"
                               onclick="#{rich:component('userAddPanel')}.hide(); return false;" />
            </p>
          </a4j:form>
          <a4j:region>
            <a4j:status id="searchStatus" startText="Searching..." stopText="" />
            <a4j:outputPanel id="searchResults" layout="block"
                             style="overflow:auto;">
              <h:outputText id="noResultsMessage" rendered="#{empty languageTeamAction.searchResults}" value="No results to display." />
              <h:form rendered="#{not empty languageTeamAction.searchResults}">
                <rich:dataTable id="personTable"
                                value="#{languageTeamAction.searchResults}" var="person">
                  <f:facet name="header">#{messages['jsf.SearchResults']}</f:facet>
                  <rich:column sortBy="#{person.name}">
                    <f:facet name="header">#{messages['jsf.Name']}</f:facet>
                    #{person.name}
                  </rich:column>
                  <rich:column sortBy="#{person.account.username}">
                    <f:facet name="header">#{messages['jsf.Username']}</f:facet>
                    #{person.account.username}
                  </rich:column>
                  <rich:column>
                    <f:facet name="header"></f:facet>
                    <h:commandButton value="#{messages['jsf.Add']}"
                                     action="#{languageTeamAction.addTeamMember(person.id)}"
                                     rendered="#{!languageTeamAction.isPersonInTeam(person.id)}" />
                    <h:outputText value="#{messages['jsf.AlreadyInTeam']}"
                                  rendered="#{languageTeamAction.isPersonInTeam(person.id)}" />
                  </rich:column>
                </rich:dataTable>
              </h:form>
            </a4j:outputPanel>
          </a4j:region>
        </f:subview>
      </rich:modalPanel>

    </ui:define>

</ui:composition>

server/zanata-war/src/main/webapp/language/request_to_join.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
   xmlns:s="http://jboss.com/products/seam/taglib"
   xmlns:ui="http://java.sun.com/jsf/facelets"
   xmlns:f="http://java.sun.com/jsf/core"
   xmlns:h="http://java.sun.com/jsf/html"
   xmlns:a4j="http://richfaces.org/a4j"
   xmlns:rich="http://richfaces.org/rich"
   template="/WEB-INF/layout/template.xhtml">

   <ui:param name="showGlobalMessages" value="true"/>
   
   <ui:define name="center_content">
      <rich:jQuery selector="#tab_tribes" query="addClass('ui-tabs-selected')" />
      <h:form>
         <s:token allowMultiplePosts="true" />
         <h1>#{messages['jsf.RequestToJoinLanguageTeamTitle']}</h1>
         <rich:panel>
            
            <s:decorate id="nameField" template="../WEB-INF/layout/display.xhtml">
               <ui:define name="label">#{messages['jsf.email.From']}</ui:define>
               <h:outputText id="senderName" value="#{sendEmail.fromName}"
                             required="true" />
            </s:decorate>

            <s:decorate id="replyEmailField" template="../WEB-INF/layout/display.xhtml">
               <ui:define name="label">#{messages['jsf.email.ReplyAddress']}<br/>#{messages['jsf.email.ReplyAddress.description']}</ui:define>
               <h:outputText id="email" value="#{sendEmail.replyEmail}" required="true" />
            </s:decorate>
            
            <s:decorate id="subjectField" template="../WEB-INF/layout/display.xhtml">
               <ui:define name="label">#{messages['jsf.email.Subject']}</ui:define>
               <h:outputText id="subject" value="#{messages['jsf.email.joinrequest.Subject']}"
                            required="true" />
            </s:decorate>
            
            <s:decorate id="messageField" template="../WEB-INF/layout/edit.xhtml">
               <ui:define name="label">#{messages['jsf.email.joinrequest.AdditionalInfo']}</ui:define>
               <h:graphicImage id="slugHelp" value="/public-img/msginfo.png" styleClass="input_help">
	             <rich:toolTip>
	               #{messages['jsf.email.joinrequest.AdditionalInfoMessage']}
	             </rich:toolTip>
	           </h:graphicImage>
	           <br/><br/>
               <rich:editor id="message" width="400" height="300"
                            style="width:400px;" required="false"
                            value="#{sendEmail.htmlMessage}" viewMode="visual"
                            useSeamText="false" configuration="richeditor" theme="advanced">
               </rich:editor>
            </s:decorate>

            <div style="clear: both"></div>
            <div class="actionButtons">
               <h:commandButton id="send" value="#{messages['jsf.email.Send']}"
                                action="#{sendEmail.send}" />

               <s:button id="cancel" value="#{messages['jsf.Cancel']}"
                         propagation="none" action="#{sendEmail.cancel}" />
            </div>

         </rich:panel>
      </h:form>

   </ui:define>

</ui:composition>