server/zanata-war/src/main/java/org/zanata/action/ProjectAction.java
/*
 * Copyright 2010, Red Hat, Inc. and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.zanata.action;

import java.io.Serializable;

import javax.faces.model.DataModel;

import org.jboss.seam.ScopeType;
import org.jboss.seam.annotations.In;
import org.jboss.seam.annotations.Logger;
import org.jboss.seam.annotations.Name;
import org.jboss.seam.annotations.Scope;
import org.jboss.seam.faces.FacesMessages;
import org.jboss.seam.log.Log;
import org.jboss.seam.security.Identity;
import org.zanata.dao.ProjectDAO;
import org.zanata.model.HProject;
import org.zanata.security.BaseSecurityChecker;

@Name("projectAction")
@Scope(ScopeType.PAGE)
public class ProjectAction extends BaseSecurityChecker implements Serializable
{
   private static final long serialVersionUID = 1L;
   private ProjectPagedListDataModel projectPagedListDataModel = new ProjectPagedListDataModel(false);
   private ProjectPagedListDataModel filteredProjectPagedListDataModel = new ProjectPagedListDataModel(true);

   private int scrollerPage = 1;

   @Logger
   Log log;

   @In
   private ProjectDAO projectDAO;

   @In
   Identity identity;

   private boolean showObsolete = false;

   private HProject securedEntity = null;

   public boolean getEmpty()
   {
      if (checkViewObsoleteOption() && showObsolete)
      {
         return projectDAO.getProjectSize() == 0;

      }
      else
      {
         return projectDAO.getFilteredProjectSize() == 0;
      }
   }

   public int getPageSize()
   {
      if (checkViewObsoleteOption() && showObsolete)
      {
         return filteredProjectPagedListDataModel.getPageSize();
      }
      else
      {
         return projectPagedListDataModel.getPageSize();
      }
   }

   public int getScrollerPage()
   {
      return scrollerPage;
   }

   public void setScrollerPage(int scrollerPage)
   {
      this.scrollerPage = scrollerPage;
   }

   public DataModel getProjectPagedListDataModel()
   {
      if (checkViewObsoleteOption() && showObsolete)
      {
         return filteredProjectPagedListDataModel;
      }
      else
      {
         return projectPagedListDataModel;
      }
   }

   public void updateObsolete(HProject project)
   {
      securedEntity = project;
      if (checkPermission("mark-obsolete"))
      {
         projectDAO.makePersistent(project);
         projectDAO.flush();

         if (project.isObsolete())
         {
            FacesMessages.instance().add("Marked {0} as obsolete", project.getName());
         }
         else
         {
            FacesMessages.instance().add("Marked {0} as current", project.getName());
         }
      }
      securedEntity = null;
   }

   public boolean isShowObsolete()
   {
      return showObsolete;
   }
   
   public void setShowObsolete(boolean showObsolete)
   {
      this.showObsolete = showObsolete;
   }

   @Override
   public Object getSecuredEntity()
   {
      return securedEntity;
   }

   /**
    * Check permission with target object name and operation
    * 
    * @param operation
    * @return
    */
   public boolean checkViewObsoleteOption()
   {
      return identity != null && identity.hasPermission("HProject", "view-obsolete-option", null);
   }

}

server/zanata-war/src/main/webapp/project/add_iteration.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:s="http://jboss.com/products/seam/taglib"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:rich="http://richfaces.org/rich"
    template="../WEB-INF/layout/template.xhtml">

<ui:define name="center_content">
    <rich:jQuery selector="#tab_projects" query="addClass('ui-tabs-selected')" />
    <h1>#{messages['jsf.NameCreateANewVersion']}</h1>

    <ui:include src="../WEB-INF/layout/iteration_edit_form.xhtml" />

</ui:define>

</ui:composition>

server/zanata-war/src/main/webapp/project/assign_maintainer.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:s="http://jboss.com/products/seam/taglib"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:rich="http://richfaces.org/rich"
    xmlns:a4j="http://richfaces.org/a4j"
    template="../WEB-INF/layout/template.xhtml">
   
    <ui:define name="left_content">
		<s:link view="/project/maintainerdetail.xhtml"
          value="#{messages['jsf.AddMaintainer']}"
        />
    </ui:define>
   
    <ui:define name="center_content">
        
      <script type="text/javascript">
        function confirmDelete()
        {
          return confirm("#{messages['jsf.AreYouSureYouWishToDeleteThisPersonThisActionCannotBeUndone']}");
        }
      </script>
      <rich:panel rendered="#{projectMaintainerManageAction.checkPermission('update')}">
        <f:facet name="header">#{messages['jsf.ProjectMaintainerManager']}</f:facet>
		<h:messages />
		
        <h:form>
            <s:token allowMultiplePosts="true" />
	        <rich:dataTable 
	            id="threads"
	            value="#{allList}" 
	            var="maintainer">
	
	          <rich:column width="auto">
	            <f:facet name="header">#{messages['jsf.Username']}</f:facet>
	            #{maintainer.account.username}
	          </rich:column>
	          <rich:column width="auto">
	            <f:facet name="header">#{messages['jsf.Name']}</f:facet>
	            #{maintainer.name}
	          </rich:column>
	          <rich:column width="auto">
	            <f:facet name="header">#{messages['jsf.Email']}</f:facet>
	            #{maintainer.email}
	          </rich:column>
	          <rich:column width="auto">
	            <f:facet name="header">#{messages['jsf.Actions']}</f:facet>          
	            <h:commandLink value="#{messages['jsf.Remove']}" action="#{projectMaintainerManageAction.deleteMaintainer(projectMaintainerManageAction.selectedPerson)}"
	                      onclick="return confirmDelete()"/>
	          </rich:column>
	  	    </rich:dataTable>
        </h:form>              
      </rich:panel>
    </ui:define>
    
  </ui:composition>

server/zanata-war/src/main/webapp/project/create_project.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:s="http://jboss.com/products/seam/taglib"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:rich="http://richfaces.org/rich"
    template="../WEB-INF/layout/template.xhtml">

<ui:define name="center_content">
    <rich:jQuery selector="#tab_projects" query="addClass('ui-tabs-selected')" />
    <h1>#{messages['jsf.CreateANewProject']}</h1>

    <ui:include src="../WEB-INF/layout/project_edit_form.xhtml" />

</ui:define>

</ui:composition>

server/zanata-war/src/main/webapp/project/edit.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:s="http://jboss.com/products/seam/taglib"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:rich="http://richfaces.org/rich"
    template="../WEB-INF/layout/template.xhtml">

<ui:define name="center_content">
    <rich:jQuery selector="#tab_projects" query="addClass('ui-tabs-selected')" />
    <h1>#{projectHome.instance.name}</h1>

    <ui:include src="../WEB-INF/layout/project_edit_form.xhtml" />

</ui:define>

</ui:composition>

server/zanata-war/src/main/webapp/project/home.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:s="http://jboss.com/products/seam/taglib"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:rich="http://richfaces.org/rich"
    xmlns:a4j="http://richfaces.org/a4j"
    template="../WEB-INF/layout/template.xhtml">

  <ui:define name="left_content">
    <rich:panel rendered="#{identity.loggedIn}">
      <f:facet name="header">#{messages['jsf.Actions']}</f:facet>
      <s:link styleClass="action_link"
      				rendered="#{projectHome.checkPermission('insert')}"
      				value="#{messages['jsf.CreateProject']}"
                    view="/project/create_project.xhtml"
                    propagation="none"/>
    </rich:panel>
  </ui:define>

  <ui:define name="center_content" >
    <s:decorate id="main_content">
    <rich:jQuery selector="#tab_projects" query="addClass('ui-tabs-selected')" />
    <s:fragment rendered="#{projectAction.getEmpty()}">
	<h:outputText value="#{messages['jsf.NoProjectExists']}" />
    </s:fragment>
    <s:fragment rendered="#{!projectAction.getEmpty()}">
      <a4j:form>
      
	 <rich:datascroller align="center" for="projectList" maxPages="10"
		    page="#{projectAction.scrollerPage}" id="scroller" reRender="sc2" />
	<rich:spacer height="15" />
        
         <s:div rendered="#{projectAction.checkViewObsoleteOption()}" styleClass="showObsoleteOption">
            <a4j:region>
            <h:selectBooleanCheckbox title="Show obsolete projects" value="#{projectAction.showObsolete}" >
                <a4j:support event="onchange" reRender="main_content" />
            </h:selectBooleanCheckbox>
            </a4j:region>
            <h:outputText value="#{messages['jsf.ShowObsolete']}"/>
        </s:div>
        
        <rich:dataTable id="projectList" 
            rows="#{projectAction.pageSize}"
            value="#{projectAction.projectPagedListDataModel}" var="project">
                <rich:column width="270px" sortBy="#{project.name}">
                     <f:facet name="header">Project Name</f:facet>
                           
                        <s:link id="project" styleClass="table_link" value="#{project.name}"  propagation="none"
                             view="/project/project.xhtml" rendered="#{!project.obsolete}"> 
                            <f:param name="slug" value="#{project.slug}"/>
                        </s:link>
                        
                        <s:link id="obsoleteProject" styleClass="table_link obsolete_link" value="#{project.name}"  propagation="none"
                             view="/project/project.xhtml" rendered="#{project.obsolete}"> 
                            <f:param name="slug" value="#{project.slug}"/>
                        </s:link>
                    </rich:column>
                <rich:column width="270px">
                        <f:facet name="header">Description</f:facet>
                        <h:outputText value="#{project.description}" />
                    </rich:column>
                <rich:column sortBy="#{project.creationDate}" width="auto">
                        <f:facet name="header">Creation Date</f:facet>
                        <h:outputText value="#{project.creationDate}">
                           <f:convertDateTime type="date" dateStyle="default"/>
                        </h:outputText>                     
                    </rich:column>
                    
                    <rich:column styleClass="centered" width="60px" sortBy="#{project.obsolete}" rendered="#{projectAction.checkViewObsoleteOption() and projectAction.showObsolete}">
                        <f:facet name="header">Obsolete</f:facet>
                        <h:selectBooleanCheckbox id="obsolete" value="#{project.obsolete}">
                            <a4j:support event="onclick"
                            ajaxSingle="true" reRender="main_content"
                            action="#{projectAction.updateObsolete(project)}"/>
                        </h:selectBooleanCheckbox>                     
                    </rich:column>
        </rich:dataTable>
        
        <rich:spacer height="15" />
	 <rich:datascroller align="center" for="projectList" maxPages="10"
		    page="#{projectAction.scrollerPage}" id="sc2" reRender="scroller" />    
	</a4j:form>
</s:fragment>
    </s:decorate>
  </ui:define>

</ui:composition>

server/zanata-war/src/main/webapp/project/homepage_edit.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:s="http://jboss.com/products/seam/taglib"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:rich="http://richfaces.org/rich"
    template="../WEB-INF/layout/template.xhtml">

	<ui:define name="center_content">
	    <rich:jQuery selector="#tab_projects" query="addClass('ui-tabs-selected')" />
	    <h1>#{projectHome.instance.name}</h1>
	
	    <h:form>
		    <rich:panel>
		      
		      <div class="prop">
	            <s:label styleClass="name">#{messages['jsf.HomepageContent']}</s:label>
	            <h:inputTextarea id="homeContent"
	                required="false"
	                value="#{projectHome.instance.homeContent}"
	                styleClass="code_editor" />
	          </div>		
	          
		    </rich:panel>
		
		    <div class="actionButtons">
		        <h:commandButton id="update"
		                      value="#{messages['jsf.Update']}"
		                     action="#{projectHome.update}"
		                   rendered="#{projectHome.managed}"/>
		        <s:button id="cancel"
		                      value="#{messages['jsf.Cancel']}"
		                propagation="none"
		                     action="#{projectHome.cancel}"/>
		    </div>
	    </h:form>
	
	</ui:define>
	
	<ui:define name="left_content">
	</ui:define>

</ui:composition>

server/zanata-war/src/main/webapp/project/iteration_edit.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:s="http://jboss.com/products/seam/taglib"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:rich="http://richfaces.org/rich"
    template="../WEB-INF/layout/template.xhtml">

<ui:define name="center_content">
    <rich:jQuery selector="#tab_projects" query="addClass('ui-tabs-selected')" />
    <h1>#{projectIterationHome.instance.slug}</h1>

    <ui:include src="../WEB-INF/layout/iteration_edit_form.xhtml" />

</ui:define>

</ui:composition>

server/zanata-war/src/main/webapp/project/iteration_files.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:s="http://jboss.com/products/seam/taglib"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:rich="http://richfaces.org/rich"
    xmlns:a4j="http://richfaces.org/a4j"
    template="../WEB-INF/layout/template.xhtml">

    <ui:define name="head">
        <script type="text/javascript">
        function downloadAllFilesClick()
        {
            if( confirm("#{messages['jsf.iteration.files.ConfirmDownloadAllFiles']}") )
            {
        	    #{rich:component('downloadProgressPanel')}.show();
        	    return true;
            }
            else
            {
                return false;	
            }
        }
        </script>
    </ui:define>

	<ui:define name="center_content">
	    <rich:jQuery selector="#tab_projects" query="addClass('ui-tabs-selected')" />
	
	    <h1>
	       #{messages['jsf.ProjectId']}:&nbsp;
	       <s:link view="/project/view/#{projectIterationFilesAction.projectSlug}">
	           #{projectIterationFilesAction.projectSlug}
	       </s:link>
	    </h1>
        <h1>
            #{messages['jsf.Iteration']}:&nbsp;
            <s:link view="/project/view/#{projectIterationFilesAction.projectSlug}">
                #{projectIterationFilesAction.iterationSlug}
            </s:link>
        </h1>
        <h1>
            #{messages['jsf.iteration.files.LocaleId']}:&nbsp;
            <s:link view="/language/view/#{projectIterationFilesAction.localeId}">
                #{projectIterationFilesAction.localeId}
            </s:link>
        </h1>
	
	    <rich:panel id="iteration-files-panel">
	        <f:facet name="header">
	            #{messages['jsf.iteration.files.PanelTitle']}
	        </f:facet>
	        <h:messages />
	        
	        <h:form>
	          <s:token allowMultiplePosts="true" />
	          <rich:datascroller id="data_table_scroller" align="center" for="data_table" 
	                   rendered="#{projectIterationFilesAction.iterationDocuments.size() > 20}">
	          </rich:datascroller>
              <rich:spacer height="20" />
              <h:outputText value="#{messages['jsf.iteration.files.NoFiles']}" 
                      rendered="#{projectIterationFilesAction.iterationDocuments.size() == 0}"/>
	          <rich:dataTable id="data_table" width="100%" value="#{projectIterationFilesAction.iterationDocuments}" 
	                  var="doc"
	                  styleClass="iteration_inline_tribes"
	                  rowClasses="odd,even"
	                  rows="20"
	                  rendered="#{projectIterationFilesAction.iterationDocuments.size() gt 0}">
	                <rich:column sortOrder="ASCENDING">
                        <f:facet name="header">#{messages['jsf.iteration.files.Path']}</f:facet>
                        #{doc.path}
                    </rich:column>
	                <rich:column filterMethod="#{projectIterationFilesAction.filterDocumentByName}">
	                    <f:facet name="header">
	                       <h:panelGroup>
	                           <h:outputText value="#{messages['jsf.Name']}"/>
	                           <br/>
	                           <h:inputText value="#{projectIterationFilesAction.documentNameFilter}" id="name_filter_input">
                                    <a4j:support event="onkeyup" reRender="data_table,data_table_scroller" ignoreDupResponses="true" requestDelay="700" focus="name_filter_input" />
                               </h:inputText>
                           </h:panelGroup>
	                    </f:facet>
	                    <s:link view="/rest/file/translation/#{projectIterationFilesAction.projectSlug}/#{projectIterationFilesAction.iterationSlug}/#{projectIterationFilesAction.localeId}/po">
	                       <f:param name="docId" value="#{doc.docId}"/>
	                       <h:outputText value="#{doc.name}"/>
	                    </s:link> 
	                </rich:column>
	                <rich:column>
	                    <f:facet name="header">#{messages['jsf.iteration.files.Statistics']}</f:facet>
	                    <ui:param name="tstatus" value="#{projectIterationFilesAction.getTransUnitWordsForDocument(doc)}" />
	                    <ui:include src="../WEB-INF/layout/statsbar.xhtml">
	                        <ui:param name="status" value="#{tstatus}" />
	                    </ui:include>
	                </rich:column>
	          </rich:dataTable>
	        </h:form>              
	    </rich:panel>
	    
	    <rich:modalPanel id="downloadProgressPanel"
	       moveable="#{false}"
           resizeable="#{false}"
           autosized="#{true}">
	       
	       <f:facet name="header">
	           <h:outputText value="#{messages['jsf.iteration.files.ProcessDlgTitle']}"/>
	       </f:facet>
	       <a4j:form>
		       <rich:progressBar id="downloadProgressBar"
		            value="#{projectIterationZipFileAction.zipFilePrepHandle.currentProgress}"
	                interval="500" 
	                label="#{projectIterationZipFileAction.zipFilePrepHandle.currentProgress} of #{projectIterationZipFileAction.zipFilePrepHandle.maxProgress}"
	                minValue="-1" 
	                maxValue="#{projectIterationZipFileAction.zipFilePrepHandle.maxProgress - 1}"
	                enabled="#{projectIterationZipFileAction.zipFilePrepHandle.inProgress}"
	                reRenderAfterComplete="downloadProgressBar">
	                <f:facet name="complete">
	                    <script type="text/javascript">
	                        #{rich:component('downloadProgressPanel')}.hide();
	                        window.location = "#{facesContext.externalContext.requestContextPath}/rest/file/download/#{projectIterationZipFileAction.zipFilePrepHandle.downloadId}";
	                    </script>
	                </f:facet>
	           </rich:progressBar>
	           <div align="right">
	               <a4j:commandButton id="closeProgressPanelButton" 
	                    action="#{projectIterationZipFileAction.cancelFileDownload}"
	                    value="#{messages['jsf.Cancel']}"
	                    reRender="downloadProgressBar">
	                    <rich:componentControl for="downloadProgressPanel" 
	                       attachTo="closeProgressPanelButton" operation="hide" event="onclick"/>
	               </a4j:commandButton>
	           </div>
	       </a4j:form>
	    </rich:modalPanel>
	</ui:define>
	
	<ui:define name="left_content">
	   
	   <rich:panel id="loggedIn" rendered="#{identity.loggedIn}">
	      <f:facet name="header">#{messages['jsf.Actions']}</f:facet>
	      <a4j:form>
		      <a4j:commandLink styleClass="action_link"
		         value="#{messages['jsf.iteration.files.DownloadAllFiles']}"
	             action="#{projectIterationZipFileAction.prepareIterationZipFile}"
	             onclick="if(!downloadAllFilesClick()){ return false; }"
	             reRender="downloadProgressBar"/>
	      </a4j:form>
	   </rich:panel>
	   
	</ui:define>

</ui:composition>

server/zanata-war/src/main/webapp/project/iteration_status.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:s="http://jboss.com/products/seam/taglib"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:rich="http://richfaces.org/rich"
    xmlns:a4j="http://richfaces.org/a4j"
    template="../WEB-INF/layout/template.xhtml">
   
 
    <ui:define name="center_content">
      <rich:jQuery selector="#tab_projects" query="addClass('ui-tabs-selected')" />
      <rich:panel id="iteration-status-panel">
        <f:facet name="header">#{messages['jsf.TranslationStatistics']}</f:facet>
		<h:messages />
		
        <h:form>
            <s:token allowMultiplePosts="true" />
		  <rich:dataTable id="data_table" width="100%" value="#{viewAllStatusAction.getAllStatus().toArray()}" 
                  var="language"
                  styleClass="iteration_inline_tribes"
                  rowClasses="odd,even">
					<rich:column sortBy="#{language.locale}">
						<f:facet name="header">#{messages['jsf.Language']}</f:facet>
	            		#{language.locale}
	        		</rich:column>
					<rich:column sortBy="#{language.nativeName}">
						<f:facet name="header">#{messages['jsf.Name']}</f:facet>
	            		#{language.nativeName}
	        		</rich:column>
	        	<rich:column sortBy="#{language.per}">
	        	  <f:facet name="header">Percentage</f:facet>
                  <ui:param name="tstatus" value="#{language.words}" />
                  <ui:include src="../WEB-INF/layout/statsbar.xhtml">
                    <ui:param name="status" value="#{tstatus}" />
                  </ui:include>
                </rich:column>
    
				<rich:column>
					<f:facet name="header">Approved (words)</f:facet>
					#{language.words.approved}
	        		</rich:column>
				<rich:column>
					<f:facet name="header">Need Review (words)</f:facet>
					#{language.words.needReview}
	        		</rich:column>
				<rich:column>
					<f:facet name="header">Untranslated (words)</f:facet>
					#{language.words.untranslated}
	        		</rich:column>
  		  </rich:dataTable>
        </h:form>              
      </rich:panel>
    </ui:define>
    
  </ui:composition>

server/zanata-war/src/main/webapp/project/maintainerdetail.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:s="http://jboss.com/products/seam/taglib"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:a4j="http://richfaces.org/a4j"
	template="../WEB-INF/layout/template.xhtml">

	<ui:define name="center_content" >
	    <h:form>
  	    <s:token allowMultiplePosts="true" />
            <rich:panel rendered="#{projectMaintainerManageAction.checkPermission('update')}">
	    <h:panelGrid>
	      <f:facet name="header">#{messages['jsf.AddMaintainer']}</f:facet>
		<s:decorate id="userField"
			template="../WEB-INF/layout/edit.xhtml">
			<ui:define name="label">#{messages['jsf.Username']}</ui:define>
	        <h:inputText id="input" value="#{accountSearch.projectMaintainer}" size="40">
				<a4j:support event="onblur" reRender="output" action="#{accountSearch.update}" />
			</h:inputText>
		  <rich:suggestionbox width="290" suggestionAction="#{accountSearch.search}" var="account" for="input">
			  <h:column>
				   <h:outputText value="#{account.username}"/>
			  </h:column>
	      </rich:suggestionbox>
              </s:decorate>
	    </h:panelGrid>
				<div>
				<h:panelGrid id="output" >
					<s:decorate id="output1" template="../WEB-INF/layout/display.xhtml">
						<ui:define name="label">#{messages['jsf.Name']} </ui:define>
						<h:outputText value="#{accountSearch.person.name}" />
					</s:decorate>
					<s:decorate id="output2" template="../WEB-INF/layout/display.xhtml">
						<ui:define name="label">#{messages['jsf.Email']} </ui:define>
						<h:outputText value="#{accountSearch.person.email}" />
					</s:decorate>
				</h:panelGrid>
				</div>


	    <div style="clear: both" />

	    <div class="actionButtons">
		<h:commandButton
	   		value="#{messages['jsf.Save']}"
			action="#{projectMaintainerManageAction.addMaintainers(accountSearch.projectMaintainer)}" /> 
		<s:button
			view="/project/assign_maintainer.xhtml"
			value="#{messages['jsf.Cancel']}" propagation="none"  action="#{projectMaintainerManageAction.cancel}" />
	    </div>
		</rich:panel>
	  </h:form>
	</ui:define>

</ui:composition>