server/zanata-war/src/main/java/org/zanata/action/AdminActionBean.java
package org.zanata.action;

import org.jboss.seam.ScopeType;
import org.jboss.seam.annotations.In;
import org.jboss.seam.annotations.Name;
import org.jboss.seam.annotations.Scope;
import org.jboss.seam.annotations.Startup;
import org.jboss.seam.annotations.security.Restrict;

@Name("adminAction")
@Scope(ScopeType.APPLICATION)
@Startup
@Restrict("#{s:hasRole('admin')}")
public class AdminActionBean
{

   @In
   ReindexAsyncBean reindexAsync;

   public boolean isReindexing()
   {
      return reindexAsync.isReindexing();
   }

   public boolean isReindexError()
   {
      return reindexAsync.hasError();
   }

   public int getReindexCount()
   {
      return reindexAsync.getObjectCount();
   }

   public int getReindexProgress()
   {
      return reindexAsync.getObjectProgress();
   }

   public void reindexDatabase()
   {
      if (!reindexAsync.isReindexing())
      {
         reindexAsync.prepareReindex();
         reindexAsync.startReindex();
      }
   }

}

server/zanata-war/src/main/java/org/zanata/action/LanguageManagerAction.java
/*
 * Copyright 2010, Red Hat, Inc. and individual contributors as indicated by the
 * @author tags. See the copyright.txt file in the distribution for a full
 * listing of individual contributors.
 * 
 * This is free software; you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 * 
 * This software is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this software; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA, or see the FSF
 * site: http://www.fsf.org.
 */
package org.zanata.action;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.faces.model.SelectItem;

import org.jboss.seam.ScopeType;
import org.jboss.seam.annotations.Create;
import org.jboss.seam.annotations.In;
import org.jboss.seam.annotations.Name;
import org.jboss.seam.annotations.Scope;
import org.jboss.seam.annotations.security.Restrict;
import org.zanata.common.LocaleId;
import org.zanata.service.LocaleService;

import com.ibm.icu.util.ULocale;

@Name("languageManagerAction")
@Scope(ScopeType.PAGE)
@Restrict("#{s:hasRole('admin')}")
public class LanguageManagerAction implements Serializable
{
   private static final long serialVersionUID = 1L;
   @In
   private LocaleService localeServiceImpl;
   private String language;
   private ULocale uLocale;
   private List<SelectItem> localeStringList;

   @Create
   public void onCreate()
   {
      fectchLocaleFromJava();
   }

   public String getLanguage()
   {
      return language;
   }

   public ULocale getuLocale()
   {
      return uLocale;
   }

   public void setuLocale(ULocale uLocale)
   {
      this.uLocale = uLocale;
   }

   public void setLanguage(String language)
   {
      this.language = language;
   }

   public void updateLanguage()
   {
      this.uLocale = new ULocale(this.language);
   }

   public String save()
   {
      LocaleId locale = new LocaleId(language);
      localeServiceImpl.save(locale);
      return "success";
   }

   public void fectchLocaleFromJava()
   {
      List<LocaleId> locale = localeServiceImpl.getAllJavaLanguages();
      List<SelectItem> localeList = new ArrayList<SelectItem>();
      for (LocaleId var : locale)
      {
         SelectItem op = new SelectItem(var.getId(), var.getId());
         localeList.add(op);
      }
      localeStringList = localeList;
   }

   public List<SelectItem> getLocaleStringList()
   {
      return localeStringList;
   }

}

server/zanata-war/src/main/java/org/zanata/action/ServerConfigurationBean.java
/*
 * Copyright 2010, Red Hat, Inc. and individual contributors as indicated by the
 * @author tags. See the copyright.txt file in the distribution for a full
 * listing of individual contributors.
 * 
 * This is free software; you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 * 
 * This software is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this software; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA, or see the FSF
 * site: http://www.fsf.org.
 */
package org.zanata.action;

import java.io.Serializable;

import org.hibernate.validator.Email;
import org.jboss.seam.ScopeType;
import org.jboss.seam.annotations.Create;
import org.jboss.seam.annotations.In;
import org.jboss.seam.annotations.Logger;
import org.jboss.seam.annotations.Name;
import org.jboss.seam.annotations.Scope;
import org.jboss.seam.annotations.Transactional;
import org.jboss.seam.annotations.security.Restrict;
import org.jboss.seam.core.Events;
import org.jboss.seam.faces.FacesMessages;
import org.jboss.seam.log.Log;
import org.zanata.ApplicationConfiguration;
import org.zanata.action.validator.EmailList;
import org.zanata.dao.ApplicationConfigurationDAO;
import org.zanata.model.HApplicationConfiguration;
import org.zanata.model.validator.UrlNoSlash;

@Name("serverConfigurationBean")
@Scope(ScopeType.PAGE)
@Restrict("#{s:hasRole('admin')}")
public class ServerConfigurationBean implements Serializable
{

   /**
    * 
    */
   private static final long serialVersionUID = 1L;

   @In
   ApplicationConfigurationDAO applicationConfigurationDAO;

   private String registerUrl;
   private String serverUrl;
   private String emailDomain;
   private String adminEmail;
   private String fromEmailAddr;
   private String homeContent;
   private String helpContent;
   @Logger
   Log log;


   public String getHomeContent()
   {
      HApplicationConfiguration var = applicationConfigurationDAO.findByKey(HApplicationConfiguration.KEY_HOME_CONTENT);
      return var != null ? var.getValue() : "";
   }

   public void setHomeContent(String homeContent)
   {
      this.homeContent = homeContent;
   }

   public String getHelpContent()
   {
      HApplicationConfiguration var = applicationConfigurationDAO.findByKey(HApplicationConfiguration.KEY_HELP_CONTENT);
      return var != null ? var.getValue() : "";
   }

   public void setHelpContent(String helpContent)
   {
      this.helpContent = helpContent;
   }

   @EmailList
   public String getAdminEmail()
   {
      return adminEmail;
   }

   public void setAdminEmail(String adminEmail)
   {
      this.adminEmail = adminEmail;
   }

   @Email
   public String getFromEmailAddr()
   {
      return fromEmailAddr;
   }

   public void setFromEmailAddr(String fromEmailAddr)
   {
      this.fromEmailAddr = fromEmailAddr;
   }

   public String getEmailDomain()
   {
      return emailDomain;
   }

   public void setEmailDomain(String emailDomain)
   {
      this.emailDomain = emailDomain;
   }

   public String updateHomeContent()
   {
      HApplicationConfiguration var = applicationConfigurationDAO.findByKey(HApplicationConfiguration.KEY_HOME_CONTENT);
      if (var != null)
      {
         if (homeContent == null || homeContent.isEmpty())
         {
            applicationConfigurationDAO.makeTransient(var);
         }
         else
         {
            var.setValue(homeContent);
         }
      }
      else if (homeContent != null && !homeContent.isEmpty())
      {
         HApplicationConfiguration op = new HApplicationConfiguration(HApplicationConfiguration.KEY_HOME_CONTENT, homeContent);
         applicationConfigurationDAO.makePersistent(op);
      }
      applicationConfigurationDAO.flush();
      FacesMessages.instance().add("Home content was successfully updated.");
      if (Events.exists())
      {
         Events.instance().raiseTransactionSuccessEvent(ApplicationConfiguration.EVENT_CONFIGURATION_CHANGED);
      }
      return "/home.xhtml";
   }

   public String updateHelpContent()
   {
      HApplicationConfiguration var = applicationConfigurationDAO.findByKey(HApplicationConfiguration.KEY_HELP_CONTENT);
      if (var != null)
      {
         if (helpContent == null || helpContent.isEmpty())
         {
            applicationConfigurationDAO.makeTransient(var);
         }
         else
         {
            var.setValue(helpContent);
         }
      }
      else if (helpContent != null && !helpContent.isEmpty())
      {
         HApplicationConfiguration op = new HApplicationConfiguration(HApplicationConfiguration.KEY_HELP_CONTENT, helpContent);
         applicationConfigurationDAO.makePersistent(op);
      }
      applicationConfigurationDAO.flush();
      FacesMessages.instance().add("Help page content was successfully updated.");
      if (Events.exists())
      {
         Events.instance().raiseTransactionSuccessEvent(ApplicationConfiguration.EVENT_CONFIGURATION_CHANGED);
      }
      return "/help/view.xhtml";
   }


   public String getRegisterUrl()
   {
      return registerUrl;
   }

   public void setRegisterUrl(String registerUrl)
   {
      this.registerUrl = registerUrl;
   }

   @UrlNoSlash
   public String getServerUrl()
   {
      return serverUrl;
   }

   public void setServerUrl(String serverUrl)
   {
      this.serverUrl = serverUrl;
   }

   @Create
   public void onCreate()
   {
      HApplicationConfiguration registerUrlValue = applicationConfigurationDAO.findByKey(HApplicationConfiguration.KEY_REGISTER);
      if (registerUrlValue != null)
      {
         this.registerUrl = registerUrlValue.getValue();
      }
      HApplicationConfiguration serverUrlValue = applicationConfigurationDAO.findByKey(HApplicationConfiguration.KEY_HOST);
      if (serverUrlValue != null)
      {
         this.serverUrl = serverUrlValue.getValue();
      }
      HApplicationConfiguration emailDomainValue = applicationConfigurationDAO.findByKey(HApplicationConfiguration.KEY_DOMAIN);
      if (emailDomainValue != null)
      {
         this.emailDomain = emailDomainValue.getValue();
      }
      HApplicationConfiguration adminEmailValue = applicationConfigurationDAO.findByKey(HApplicationConfiguration.KEY_ADMIN_EMAIL);
      if (adminEmailValue != null)
      {
         this.adminEmail = adminEmailValue.getValue();
      }
      HApplicationConfiguration fromAddressValue = applicationConfigurationDAO.findByKey(HApplicationConfiguration.KEY_EMAIL_FROM_ADDRESS);
      if (fromAddressValue != null)
      {
         this.fromEmailAddr = fromAddressValue.getValue();
      }

   }

   @Transactional
   public void update()
   {
      HApplicationConfiguration registerUrlValue = applicationConfigurationDAO.findByKey(HApplicationConfiguration.KEY_REGISTER);
      if (registerUrlValue != null)
      {
         if (registerUrl == null || registerUrl.isEmpty())
         {
            applicationConfigurationDAO.makeTransient(registerUrlValue);
         }
         else
         {
            registerUrlValue.setValue(registerUrl);
         }
      }
      else if (registerUrl != null && !registerUrl.isEmpty())
      {
         registerUrlValue = new HApplicationConfiguration(HApplicationConfiguration.KEY_REGISTER, registerUrl);
         applicationConfigurationDAO.makePersistent(registerUrlValue);
      }

      HApplicationConfiguration serverUrlValue = applicationConfigurationDAO.findByKey(HApplicationConfiguration.KEY_HOST);
      if (serverUrlValue != null)
      {
         if (serverUrl == null || serverUrl.isEmpty())
         {
            applicationConfigurationDAO.makeTransient(serverUrlValue);
         }
         else
         {
            serverUrlValue.setValue(serverUrl);
         }
      }
      else if (serverUrl != null && !serverUrl.isEmpty())
      {
         serverUrlValue = new HApplicationConfiguration(HApplicationConfiguration.KEY_HOST, serverUrl);
         applicationConfigurationDAO.makePersistent(serverUrlValue);
      }

      HApplicationConfiguration emailDomainValue = applicationConfigurationDAO.findByKey(HApplicationConfiguration.KEY_DOMAIN);
      if (emailDomainValue != null)
      {
         if (emailDomain == null || emailDomain.isEmpty())
         {
            applicationConfigurationDAO.makeTransient(emailDomainValue);
         }
         else
         {
            emailDomainValue.setValue(emailDomain);
         }
      }
      else if (emailDomain != null && !emailDomain.isEmpty())
      {
         emailDomainValue = new HApplicationConfiguration(HApplicationConfiguration.KEY_DOMAIN, emailDomain);
         applicationConfigurationDAO.makePersistent(emailDomainValue);
      }

      HApplicationConfiguration adminEmailValue = applicationConfigurationDAO.findByKey(HApplicationConfiguration.KEY_ADMIN_EMAIL);
      if (adminEmailValue != null)
      {
         if (adminEmail == null || adminEmail.isEmpty())
         {
            applicationConfigurationDAO.makeTransient(adminEmailValue);
         }
         else
         {
            adminEmailValue.setValue(adminEmail);
         }
      }
      else if (adminEmail != null && !adminEmail.isEmpty())
      {
         adminEmailValue = new HApplicationConfiguration(HApplicationConfiguration.KEY_ADMIN_EMAIL, adminEmail);
         applicationConfigurationDAO.makePersistent(adminEmailValue);
      }

      HApplicationConfiguration fromEmailAddrValue = applicationConfigurationDAO.findByKey(HApplicationConfiguration.KEY_EMAIL_FROM_ADDRESS);
      if (fromEmailAddrValue != null)
      {

server/zanata-war/src/main/webapp/admin/glossary.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:rich="http://richfaces.org/rich"       
    xmlns:s="http://jboss.com/products/seam/taglib">

  <ui:composition template="../WEB-INF/layout/template.xhtml">
  
    <ui:define name="center_content">
        <rich:jQuery selector="#tab_admin" query="addClass('ui-tabs-selected')" />  
        <rich:panel id="glossary-status-panel">
        <f:facet name="header">#{messages['jsf.GlossaryStatistics']}</f:facet>
        
        <h:form>
            <s:token allowMultiplePosts="true" />
            <rich:dataTable id="data_table" width="100%" value="#{glossaryStatsAction.getAllStatus().toArray()}" 
                  var="language" styleClass="iteration_inline_tribes" rowClasses="odd,even">
                    <rich:column sortBy="#{language.locale}">
                        <f:facet name="header">#{messages['jsf.Language']}</f:facet>
                        #{language.locale}
                    </rich:column>
                    <rich:column sortBy="#{language.entryCount}">
                        <f:facet name="header">#{messages['jsf.GlossaryEntries']}</f:facet>
                        #{language.entryCount}
                    </rich:column>
          </rich:dataTable>
        </h:form>              
      </rich:panel>
    
    </ui:define>
    
  </ui:composition>
</html>

server/zanata-war/src/main/webapp/admin/home.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:s="http://jboss.com/products/seam/taglib"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:rich="http://richfaces.org/rich"
    template="../WEB-INF/layout/template.xhtml">

    <ui:define name="center_content">
        <rich:jQuery selector="#tab_admin" query="addClass('ui-tabs-selected')" />
        <h1>#{messages['jsf.Administration']}</h1>
		
		#{messages['jsf.PleaseChooseAPageFromTheAdministrationMenuAbove']}
    </ui:define>
</ui:composition>

server/zanata-war/src/main/webapp/admin/languagemanager.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:s="http://jboss.com/products/seam/taglib"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:a4j="http://richfaces.org/a4j"
	template="../WEB-INF/layout/template.xhtml">

	<ui:define name="left_content">
		<s:link view="/admin/supportedlanguagedetail.xhtml"
			value="#{messages['jsf.CreateSupportedLanguage']}" />
	</ui:define>

	<ui:define name="center_content">
        <rich:jQuery selector="#tab_admin" query="addClass('ui-tabs-selected')" />
		<script type="text/javascript">
        function confirmDelete()
        {
          return confirm("#{messages['jsf.AreYouSureYouWishToDeleteThisLanguageThisActionCannotBeUndone']}");
        }
        function confirmDisable()
        {
          return confirm("#{messages['jsf.AreYouSureYouWishToDisableThisLanguage']}");
        }
        function confirmEnable()
        {
          return confirm("#{messages['jsf.AreYouSureYouWishToEnableThisLanguage']}");
        }
      </script>
		<rich:panel>
			<f:facet name="header">#{messages['jsf.LanguageManager']}</f:facet>

			<a4j:form>
				<s:token allowMultiplePosts="true" />
				<rich:dataTable id="threads" value="#{allLanguages}"
					var="language">

					<rich:column sortBy="#{language.localeId.id}">
						<f:facet name="header">#{messages['jsf.Language']}</f:facet>
	            		#{language.localeId.id}
	        		</rich:column>
					<rich:column sortBy="#{language.retrieveDisplayName()}">
						<f:facet name="header">#{messages['jsf.Name']}</f:facet>
	            		#{language.retrieveDisplayName()}
	        		</rich:column>
					<rich:column >
						<f:facet name="header">#{messages['jsf.NativeName']}</f:facet>
	            		#{language.retrieveNativeName()}
	        		</rich:column>
					<rich:column>
						<f:facet name="header">#{messages['jsf.Actions']}</f:facet>
						<h:commandButton value="#{messages['jsf.Disabled']}"
							rendered="#{language.active}" 
							action="#{languageSearchAction.disable(languageSearchAction.selectedLanguage)}"
							onclick="return confirmDisable()" />
						<h:commandButton value="#{messages['jsf.Enable']}" 
							rendered="#{!language.active}"
							action="#{languageSearchAction.enable(languageSearchAction.selectedLanguage)}"
							onclick="return confirmEnable()" />
						<h:commandButton value="#{messages['jsf.TeamMembers']}" 
							action="#{languageSearchAction.manageMembers(languageSearchAction.selectedLanguage)}">
							<f:param name="id" value="#{language.localeId.id}" />
						</h:commandButton>
					</rich:column>
				</rich:dataTable>
			</a4j:form>
		</rich:panel>
	</ui:define>

</ui:composition>

server/zanata-war/src/main/webapp/admin/roledetail.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:rich="http://richfaces.org/rich"       
    xmlns:s="http://jboss.com/products/seam/taglib">

  <ui:composition template="../WEB-INF/layout/template.xhtml">
  
    <ui:define name="center_content">
      <rich:jQuery selector="#tab_admin" query="addClass('ui-tabs-selected')" />
  
      <h:form>
        <s:token allowMultiplePosts="true" />
        <rich:panel>
          <f:facet name="header">#{messages['jsf.RoleDetails']}</f:facet>

          <s:decorate id="roleField" template="../WEB-INF/layout/edit.xhtml">
            <ui:define name="label">#{messages['jsf.Role']}</ui:define>
            <h:inputText id="role" value="#{roleAction.role}" readonly="#{identityManager.userExists(roleAction.role)}"/>
          </s:decorate>
              
          <s:decorate id="groupsField" template="../WEB-INF/layout/edit.xhtml">
            <ui:define name="label">#{messages['jsf.MemberOf']}</ui:define>
              <h:selectManyCheckbox id="groups" value="#{roleAction.groups}" layout="pageDirection">
                <s:selectItems value="#{identityManager.listRoles()}" var="role" label="#{role}"/>
              </h:selectManyCheckbox>
          </s:decorate>
              
          <div style="clear:both"/>

          <div class="actionButtons">
            <h:commandButton value="#{messages['jsf.Save']}" action="#{roleAction.save}"/>
            <s:button view="/admin/rolemanager.xhtml" value="#{messages['jsf.Cancel']}" propagation="end"/>
          </div>
    
        </rich:panel>
      </h:form>
	    
    </ui:define>
    
  </ui:composition>
</html>

server/zanata-war/src/main/webapp/admin/rolemanager.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"    
    xmlns:rich="http://richfaces.org/rich" 
    xmlns:a4j="http://richfaces.org/a4j"
    xmlns:s="http://jboss.com/products/seam/taglib">

  <ui:composition template="../WEB-INF/layout/template.xhtml">
   
    <ui:define name="left_content">
        <s:link action="#{roleAction.createRole}" 
          rendered="#{s:hasPermission('seam.account', 'create', null)}"
          value="#{messages['jsf.CreateRole']}"
        />
    </ui:define>
   
    <ui:define name="center_content">
      <rich:jQuery selector="#tab_admin" query="addClass('ui-tabs-selected')" />
      <script type="text/javascript">
        function confirmDelete()
        {
          return confirm("#{messages['jsf.AreYouSureYouWishToDeleteThisRoleThisActionCannotBeUndone']}");
        }
      </script>
      <rich:panel>
        <f:facet name="header">#{messages['jsf.RoleManager']}</f:facet>

        <h:form>
            <s:token allowMultiplePosts="true" />
	        <h:dataTable 
	            id="threads"
	            value="#{roles}" 
	            var="role"
	            cellspacing="0"
	            headerClass="columnHeader"
	            rowClasses="odd,even"
	            columnClasses=",,enabled,action"
	            styleClass="fullwidth">
	
	          <h:column width="auto">
	            <f:facet name="header">#{messages['jsf.Role']}</f:facet>
	            #{role}
	          </h:column>
	          <h:column width="auto">
	            <f:facet name="header">#{messages['jsf.MemberOf']}</f:facet>
	            #{roleSearch.getRoleGroups(role)}
	          </h:column>
	          <h:column width="auto">
	            <f:facet name="header">#{messages['jsf.Actions']}</f:facet>          
	            <s:fragment rendered="#{s:hasPermission('seam.role', 'update')}">
	              <h:commandLink value="#{messages['jsf.Edit']}" action="#{roleAction.editRole(roleSearch.selectedRole)}"/><span> | </span>
	            </s:fragment>
	            <h:commandLink value="#{messages['jsf.Delete']}" action="#{identityManager.deleteRole(roleSearch.selectedRole)}"
	                    rendered="#{s:hasPermission('seam.role', 'delete')}"
	                    onclick="return confirmDelete()"/>
	          </h:column>
	  	    </h:dataTable>
        </h:form>              
      </rich:panel>
    </ui:define>
    
  </ui:composition>
</html>

server/zanata-war/src/main/webapp/admin/search.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:s="http://jboss.com/products/seam/taglib"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:rich="http://richfaces.org/rich"
    xmlns:a4j="http://richfaces.org/a4j"
    template="../WEB-INF/layout/template.xhtml">

    <ui:define name="center_content">
      <rich:jQuery selector="#tab_admin" query="addClass('ui-tabs-selected')" />
      <rich:panel>
      <h1>#{messages['jsf.Search']}</h1>
                 
        <!-- TODO reformat indentation, change button label id to match progress message id -->
        <a4j:form>
          <s:token allowMultiplePosts="true" />
          <a4j:region>
            <a4j:outputPanel id="reindexPanel">
              <h:outputText rendered="#{adminAction.reindexError}" escape="false">
                <p>#{messages['jsf.search.reindex.ErrorMessage']}</p>
              </h:outputText>
              <h:outputText rendered="#{adminAction.reindexError}" escape="false">
                <p>#{messages['jsf.search.reindex.PleaseReindex']}</p>
              </h:outputText>
              <a4j:commandButton id="reindex"
                  value="#{messages['jsf.ReindexFullTextSearchDatabase']}"
                  action="#{adminAction.reindexDatabase}"
                  rendered="#{!adminAction.reindexing}"
                  reRender="reindexPanel"/>
              <!-- minValue is -1 because of a bug when 0 is used -->
              <rich:progressBar id="reindexProgressBar"
                    value="#{adminAction.reindexProgress}"
                    interval="1000"
                    label="#{messages['jsf.search.reindex.ProgressMessage']}"
                    minValue="-1"
                    maxValue="#{adminAction.reindexCount - 1}"
                    enabled="#{adminAction.reindexing}"
                    reRenderAfterComplete="reindexPanel">
              </rich:progressBar>
            </a4j:outputPanel>
          </a4j:region>
        </a4j:form>
      </rich:panel>
    </ui:define>
    
</ui:composition>